/**
 * NVIDIA Cosmos Transfer 2.5 Video Backend
 *
 * Generates a product showcase video from an MHDL document,
 * optionally using a Hunyuan3D model artifact as input geometry.
 */

import type { MHDLDocument, BuildArtifact, ForgeConfig } from "../../schema/mhdl.js";
import { fetchWithRetry, classifyHttpError } from "../../utils/fetch-retry.js";

// ─── Prompt Builder ─────────────────────────────────────────

function buildScenePrompt(doc: MHDLDocument): string {
  const parts: string[] = [];

  parts.push(
    `A product showcase video of "${doc.meta.name}": ${doc.meta.description}.`
  );

  // Physical description
  const dims = doc.board.dimensions;
  if (dims) {
    parts.push(
      `The device is ${dims.widthMm}mm x ${dims.heightMm}mm` +
        (dims.depthMm ? ` x ${dims.depthMm}mm` : "") +
        "."
    );
  }

  const enc = doc.enclosure;
  const material = enc.material?.toUpperCase() || "PLA";
  parts.push(`It has a ${enc.type} ${material} enclosure with smooth rounded edges.`);

  // Scene setup
  parts.push(
    "The product sits on a clean, matte white surface and rotates slowly 360 degrees."
  );
  parts.push(
    "Studio lighting with soft shadows, neutral background."
  );

  // Style
  if (doc.visualization?.style) {
    parts.push(`Visual style: ${doc.visualization.style}.`);
  }

  // Background override
  if (doc.visualization?.background) {
    parts.push(`Background: ${doc.visualization.background}.`);
  }

  return parts.join(" ");
}

// ─── Offline Storyboard Generator ───────────────────────────

function generateStoryboard(doc: MHDLDocument): string {
  const dims = doc.board.dimensions;
  const enc = doc.enclosure;
  const wallT = enc.wallThicknessMm;
  const material = enc.material?.toUpperCase() || "PLA";

  const caseW = (dims?.widthMm || 60) + wallT * 2;
  const caseH = (dims?.heightMm || 40) + wallT * 2;
  const caseD = (dims?.depthMm || 20) + wallT * 2;

  // Collect visible features for close-up descriptions
  const features: string[] = [];
  for (const comp of doc.board.components) {
    switch (comp.type) {
      case "led":
      case "neopixel": {
        const color = comp.properties?.["color"] ?? "white";
        features.push(`${color} LED indicator (${comp.id})`);
        break;
      }
      case "oled":
        features.push(`OLED display (${comp.model || "128x64"})`);
        break;
      case "lcd":
        features.push(`LCD screen (${comp.model || "16x2 character"})`);
        break;
      case "button":
        features.push(`tactile push button (${comp.id})`);
        break;
      case "speaker":
        features.push(`speaker grille (${comp.id})`);
        break;
      case "buzzer":
        features.push(`buzzer opening (${comp.id})`);
        break;
      case "potentiometer":
        features.push(`rotary knob (${comp.id})`);
        break;
      default:
        break;
    }
  }

  // Collect cutout descriptions
  const cutouts = enc.cutouts.map(
    (c) => `${c.type.replace(/-/g, " ")} on ${c.wall} wall${c.componentRef ? ` (for ${c.componentRef})` : ""}`
  );

  const lines: string[] = [];

  lines.push(`# Product Showcase Video Storyboard`);
  lines.push(`## ${doc.meta.name}`);
  lines.push(``);
  lines.push(`> *Offline placeholder generated by MeshCue Forge.*`);
  lines.push(`> *For AI-generated video, set the COSMOS_ENDPOINT environment variable.*`);
  lines.push(``);
  lines.push(`### Product Details`);
  lines.push(`- **Description:** ${doc.meta.description}`);
  lines.push(`- **Enclosure:** ${enc.type} ${material} case, ${caseW}mm x ${caseH}mm x ${caseD}mm`);
  lines.push(`- **Wall thickness:** ${wallT}mm, corner radius ${enc.cornerRadiusMm}mm`);
  if (enc.labelEmboss) {
    lines.push(`- **Label:** "${enc.labelEmboss}" embossed on front`);
  }
  lines.push(``);
  lines.push(`### Scene Setup`);
  lines.push(`- Clean matte white surface, studio lighting with soft shadows`);
  if (doc.visualization?.style) {
    lines.push(`- Visual style: ${doc.visualization.style}`);
  }
  if (doc.visualization?.background) {
    lines.push(`- Background: ${doc.visualization.background}`);
  }
  lines.push(`- Resolution: 720p, 81 frames @ 24fps (~3.4s)`);
  lines.push(``);

  // Frame 1-20
  lines.push(`---`);
  lines.push(`### Frames 1-20: Wide Shot (Hero Angle)`);
  lines.push(`- Camera positioned front-left at 30 degrees, slightly elevated`);
  lines.push(`- Full product visible: ${caseW}mm x ${caseH}mm x ${caseD}mm ${material} enclosure`);
  lines.push(`- ${enc.type} case with ${enc.cornerRadiusMm}mm rounded corners`);
  if (enc.labelEmboss) {
    lines.push(`- Embossed label "${enc.labelEmboss}" visible on front face`);
  }
  if (cutouts.length > 0) {
    lines.push(`- Visible cutouts: ${cutouts.join(", ")}`);
  }
  lines.push(`- Slow dolly-in from frame 1 to 20`);
  lines.push(``);

  // Frame 21-40
  lines.push(`---`);
  lines.push(`### Frames 21-40: Close-Up on Key Features`);
  if (features.length > 0) {
    lines.push(`- Camera racks focus to highlight key external features:`);
    for (const feat of features) {
      lines.push(`  - ${feat}`);
    }
  } else {
    lines.push(`- Camera moves closer to show surface detail and material texture`);
  }
  lines.push(`- Shallow depth of field, soft bokeh background`);
  lines.push(`- Subtle shift between features over 20 frames`);
  lines.push(``);

  // Frame 41-60
  lines.push(`---`);
  lines.push(`### Frames 41-60: Slow 360-Degree Rotation`);
  lines.push(`- Product rotates on turntable, ~18 degrees per frame`);
  lines.push(`- Camera at eye level, consistent framing`);
  lines.push(`- All six sides become visible during rotation:`);
  lines.push(`  - Front: ${cutouts.filter((c) => c.includes("front")).join(", ") || "main face"}`);
  lines.push(`  - Back: ${cutouts.filter((c) => c.includes("back")).join(", ") || "rear panel"}`);
  lines.push(`  - Left: ${cutouts.filter((c) => c.includes("left")).join(", ") || "side panel"}`);
  lines.push(`  - Right: ${cutouts.filter((c) => c.includes("right")).join(", ") || "side panel"}`);
  lines.push(`  - Top: ${cutouts.filter((c) => c.includes("top")).join(", ") || "top surface"}`);
  lines.push(`  - Bottom: mounting points (${enc.mounts})`);
  lines.push(``);

  // Frame 61-81
  lines.push(`---`);
  lines.push(`### Frames 61-81: Hero Shot with Fade`);
  lines.push(`- Camera returns to original front-left hero angle`);
  lines.push(`- Product settles into final position`);
  lines.push(`- Soft fade begins at frame 72, fully faded by frame 81`);
  lines.push(`- Final frame holds the product centered in frame`);

  return lines.join("\n");
}

// ─── Main Generator ─────────────────────────────────────────

export async function generateCosmosVideo(
  doc: MHDLDocument,
  config: ForgeConfig,
  modelArtifact?: BuildArtifact
): Promise<BuildArtifact[]> {
  if (!config.cosmosEndpoint) {
    // Offline mode: generate a descriptive storyboard markdown
    const storyboard = generateStoryboard(doc);
    return [
      {
        stage: "visualization",
        filename: "product-video-storyboard.md",
        content: storyboard,
        format: "markdown",
        contentType: "text",
        backend: "cosmos-offline",
      },
    ];
  }

  const prompt = buildScenePrompt(doc);

  // Build request body
  const body: Record<string, unknown> = {
    prompt,
    num_frames: 81,
    fps: 24,
    resolution: "720p",
  };

  // If a Hunyuan3D model artifact is available, pass it as input geometry
  if (modelArtifact && modelArtifact.contentType === "base64") {
    body.input_image = modelArtifact.content;
  }

  try {
    const response = await fetchWithRetry(
      config.cosmosEndpoint,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      { timeoutMs: 30_000, maxRetries: 2, baseDelayMs: 1_000 },
    );

    if (!response.ok) {
      const classified = classifyHttpError(response.status, "Cosmos");
      const errorText = classified || await response.text().catch(() => "Unknown error");
      return [
        {
          stage: "visualization",
          filename: "product-video.mp4",
          content: `Error: Cosmos API returned HTTP ${response.status} — ${errorText}`,
          format: "error",
          contentType: "text",
          backend: "cosmos",
        },
      ];
    }

    const result = await response.json() as Record<string, unknown>;

    // Response contains base64-encoded video data
    if (typeof result.video === "string" || typeof result.data === "string" || typeof result.output === "string") {
      const base64Data = (result.video ?? result.data ?? result.output) as string;
      return [
        {
          stage: "visualization",
          filename: "product-video.mp4",
          content: base64Data,
          format: "mp4",
          contentType: "base64",
          mimeType: "video/mp4",
          backend: "cosmos",
        },
      ];
    }

    // Response contains a URL to the generated video
    if (typeof result.url === "string" || typeof result.video_url === "string") {
      const url = (result.url ?? result.video_url) as string;
      return [
        {
          stage: "visualization",
          filename: "product-video.mp4",
          content: url,
          format: "mp4",
          contentType: "url",
          mimeType: "video/mp4",
          backend: "cosmos",
        },
      ];
    }

    // Unexpected response shape
    return [
      {
        stage: "visualization",
        filename: "product-video.mp4",
        content: `Error: Unexpected Cosmos response format — ${JSON.stringify(result).slice(0, 500)}`,
        format: "error",
        contentType: "text",
        backend: "cosmos",
      },
    ];
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return [
      {
        stage: "visualization",
        filename: "product-video.mp4",
        content: `Error: Failed to call Cosmos endpoint — ${message}`,
        format: "error",
        contentType: "text",
        backend: "cosmos",
      },
    ];
  }
}
