/**
 * Medical regulatory document generators for MeshCue Forge.
 *
 * Generates WHO checklists, IEC 62304, FMEA, CE guidance,
 * and battery-life estimation documents for healthcare devices
 * targeting underdeveloped countries.
 */

import type { MHDLDocument, BuildArtifact, Component } from "../../schema/mhdl.js";
import { t, type MedicalLanguage } from "../../i18n/medical.js";

// ─── Medical Disclaimer ─────────────────────────────────────

const MEDICAL_DISCLAIMER = `> **⚠️ Disclaimer:** This document was auto-generated by MeshCue Forge as a design aid
> and starting point. It does NOT constitute regulatory approval, medical device
> certification, or clinical validation. All generated content must be reviewed by
> qualified regulatory and clinical professionals before submission to any regulatory
> body or use in patient care. MeshCue assumes no liability for clinical outcomes.`;

// ─── Helpers ────────────────────────────────────────────────

function deviceName(doc: MHDLDocument): string {
  return doc.meta.name;
}

function componentList(doc: MHDLDocument): Component[] {
  return [doc.board.mcu, ...doc.board.components];
}

function powerVoltage(doc: MHDLDocument): string {
  return `${doc.board.power.voltageIn}V`;
}

function regulatedVoltage(doc: MHDLDocument): string {
  return doc.board.power.regulatorOut
    ? `${doc.board.power.regulatorOut}V`
    : "N/A";
}

function maxCurrent(doc: MHDLDocument): string {
  return `${doc.board.power.maxCurrentMa}mA`;
}

function ipRating(doc: MHDLDocument): string {
  const enc = doc.enclosure;
  if (enc.ventilation) return "IP20 (ventilated enclosure)";
  const hasCutouts = enc.cutouts.length > 0;
  return hasCutouts ? "IP40 (cutouts present)" : "IP54 (sealed enclosure)";
}

function enclosureMaterial(doc: MHDLDocument): string {
  return (doc.enclosure.material || "pla").toUpperCase();
}

function mcuDescription(doc: MHDLDocument): string {
  const mcu = doc.board.mcu;
  return `${mcu.model || mcu.family} (${mcu.family})`;
}

/** Classify a component into a broad FMEA category. */
function fmeaCategory(comp: Component): string {
  const t = comp.type;
  if (t === "mcu") return "MCU";
  if (["led", "oled", "lcd", "neopixel"].includes(t)) return "Display";
  if (["button", "joystick", "potentiometer", "encoder"].includes(t)) return "Button";
  if (["buzzer", "speaker"].includes(t)) return "Buzzer";
  if (t === "voltage-regulator") return "Power";
  if (
    [
      "sensor",
      "temperature_sensor",
      "thermocouple",
      "moisture",
      "gas_sensor",
      "ldr",
      "pir",
      "ultrasonic",
      "gps",
      "rfid",
    ].includes(t)
  )
    return "Sensor";
  if (["connector", "antenna"].includes(t)) return "Connection";
  return "Connection"; // default bucket
}

// ─── 1. WHO Checklist ───────────────────────────────────────

export function generateWHOChecklist(doc: MHDLDocument, lang?: MedicalLanguage): BuildArtifact {
  const s = t(lang);
  const comps = componentList(doc);
  const lines: string[] = [];

  lines.push(MEDICAL_DISCLAIMER);
  lines.push(``);
  lines.push(`# ${s.whoChecklistTitle}`);
  lines.push(`## ${deviceName(doc)}`);
  lines.push(``);
  lines.push(`> ${s.autoGenerated}.`);
  lines.push(``);

  // Device Description
  lines.push(`## 1. ${s.deviceDescription}`);
  lines.push(``);
  lines.push(`- [x] Device name: **${deviceName(doc)}** (auto)`);
  lines.push(`- [x] Description: ${doc.meta.description} (auto)`);
  lines.push(`- [x] Component count: ${comps.length} (auto)`);
  lines.push(`- [ ] GMDN code (Global Medical Device Nomenclature)`);
  lines.push(`- [ ] Regulatory class in target country`);
  lines.push(`- [ ] Manufacturer name and address`);
  lines.push(`- [ ] Date of manufacture / expiry (if applicable)`);
  lines.push(``);

  // Intended Use
  lines.push(`## 2. ${s.intendedUse}`);
  lines.push(``);
  lines.push(`- [ ] Intended medical purpose`);
  lines.push(`- [ ] Target patient population`);
  lines.push(`- [ ] Intended user profile (clinician, community health worker, patient)`);
  lines.push(`- [ ] Intended environment of use (hospital, clinic, home, field)`);
  lines.push(`- [ ] Contraindications`);
  lines.push(``);

  // Performance Requirements
  lines.push(`## 3. ${s.performanceRequirements}`);
  lines.push(``);
  lines.push(`- [ ] Accuracy / precision specifications`);
  lines.push(`- [ ] Measurement range`);
  lines.push(`- [ ] Response time`);
  lines.push(`- [ ] Calibration requirements`);
  lines.push(`- [ ] Expected service life`);
  lines.push(`- [x] MCU: ${mcuDescription(doc)} (auto)`);
  lines.push(``);

  // Safety Requirements
  lines.push(`## 4. ${s.safetyRequirements}`);
  lines.push(``);
  lines.push(`- [x] Input voltage: ${powerVoltage(doc)} (auto)`);
  lines.push(`- [x] Regulated voltage: ${regulatedVoltage(doc)} (auto)`);
  lines.push(`- [x] Max current draw: ${maxCurrent(doc)} (auto)`);
  lines.push(`- [ ] Electrical safety (IEC 60601-1 compliance)`);
  lines.push(`- [ ] Biocompatibility (ISO 10993 if patient-contact)`);
  lines.push(`- [ ] Electromagnetic compatibility (IEC 60601-1-2)`);
  lines.push(`- [ ] Alarm system requirements (IEC 60601-1-8)`);
  lines.push(`- [ ] Risk management file (ISO 14971)`);
  lines.push(``);

  // Environmental Conditions
  lines.push(`## 5. ${s.environmentalConditions}`);
  lines.push(``);
  lines.push(`- [ ] Operating temperature range (recommend 5 °C – 40 °C for tropical climates)`);
  lines.push(`- [ ] Operating humidity range (recommend up to 95 % RH non-condensing)`);
  lines.push(`- [x] IP rating estimate: ${ipRating(doc)} (auto)`);
  lines.push(`- [x] Enclosure material: ${enclosureMaterial(doc)} (auto)`);
  lines.push(`- [ ] Altitude / atmospheric pressure tolerance`);
  lines.push(`- [ ] Resistance to dust, insects, and water ingress`);
  lines.push(``);

  // Packaging & Labeling
  lines.push(`## 6. ${s.packagingLabeling}`);
  lines.push(``);
  lines.push(`- [ ] Labeling language(s) appropriate for target country`);
  lines.push(`- [ ] Symbols per ISO 15223-1`);
  lines.push(`- [ ] Instructions for Use (IFU) — include pictorial instructions for low-literacy users`);
  lines.push(`- [ ] Cleaning / decontamination instructions`);
  lines.push(`- [ ] Storage conditions on packaging`);
  lines.push(`- [ ] Batch / serial number system`);
  lines.push(``);

  // Quality Management
  lines.push(`## 7. ${s.qualityManagement}`);
  lines.push(``);
  lines.push(`- [ ] ISO 13485 Quality Management System`);
  lines.push(`- [ ] Design and development plan`);
  lines.push(`- [ ] Design verification and validation records`);
  lines.push(`- [ ] Production and process controls`);
  lines.push(`- [ ] Corrective and Preventive Action (CAPA) procedure`);
  lines.push(``);

  // Components
  lines.push(`## 8. ${s.componentSummary}`);
  lines.push(``);
  lines.push(`| # | ${s.component} | ${s.type} | ${s.model} |`);
  lines.push(`|---|-----------|------|-------|`);
  comps.forEach((c, i) => {
    lines.push(`| ${i + 1} | ${c.id} | ${c.type} | ${c.model || "—"} |`);
  });
  lines.push(``);

  // WHO prequalification notes
  lines.push(`## WHO Prequalification Guidance for Developing Countries`);
  lines.push(``);
  lines.push(`- Refer to WHO Prequalification of In Vitro Diagnostics (if applicable)`);
  lines.push(`- Consider WHO Essential Diagnostics List (EDL) alignment`);
  lines.push(`- Design for low-resource settings: minimal training, robust power options,`);
  lines.push(`  visual + audible feedback, easy maintenance`);
  lines.push(`- Ensure spare parts are locally sourced where possible`);
  lines.push(`- Document cold-chain requirements (if any)`);
  lines.push(`- Include field-repair documentation with pictorial guides`);
  lines.push(`- Consider connectivity requirements for health information systems (DHIS2, OpenMRS)`);
  lines.push(`- Plan for end-of-life disposal per local e-waste regulations`);

  return {
    stage: "docs",
    filename: "WHO_CHECKLIST.md",
    content: lines.join("\n"),
    format: "markdown",
  };
}

// ─── 2. IEC 62304 ───────────────────────────────────────────

export function generateIEC62304Doc(doc: MHDLDocument, lang?: MedicalLanguage): BuildArtifact {
  const s = t(lang);
  const comps = componentList(doc);
  const mcu = doc.board.mcu;
  const fw = doc.firmware;
  const lines: string[] = [];

  lines.push(MEDICAL_DISCLAIMER);
  lines.push(``);
  lines.push(`# ${s.iec62304Title}`);
  lines.push(`## ${deviceName(doc)}`);
  lines.push(``);
  lines.push(`> ${s.autoGenerated}.`);
  lines.push(``);

  // Software System Overview
  lines.push(`## 1. Software System Overview`);
  lines.push(``);
  lines.push(`- **Device**: ${deviceName(doc)}`);
  lines.push(`- **Description**: ${doc.meta.description}`);
  lines.push(`- **Firmware framework**: ${fw.framework} (auto)`);
  lines.push(`- **Entry point**: ${fw.entrypoint} (auto)`);
  lines.push(`- **MCU family**: ${mcu.family} (auto)`);
  lines.push(`- **MCU model**: ${mcu.model || mcu.family} (auto)`);
  if (mcu.clockMhz) lines.push(`- **Clock**: ${mcu.clockMhz} MHz (auto)`);
  if (mcu.flashKb) lines.push(`- **Flash**: ${mcu.flashKb} KB (auto)`);
  if (mcu.ramKb) lines.push(`- **RAM**: ${mcu.ramKb} KB (auto)`);
  if (mcu.wireless?.length) lines.push(`- **Wireless**: ${mcu.wireless.join(", ")} (auto)`);
  lines.push(``);
  lines.push(`### Software purpose`);
  lines.push(`<!-- Describe the clinical purpose of the software -->`);
  lines.push(``);

  // Software Architecture
  lines.push(`## 2. Software Architecture (auto-generated)`);
  lines.push(``);
  lines.push(`\`\`\``);
  lines.push(`┌─────────────────────────────────────┐`);
  lines.push(`│           Application Layer          │`);
  lines.push(`│  (${fw.entrypoint})${" ".repeat(Math.max(0, 30 - fw.entrypoint.length))}│`);
  lines.push(`├─────────────────────────────────────┤`);
  lines.push(`│           Library Layer              │`);
  for (const lib of fw.libraries) {
    const label = `│  ${lib.name}${lib.version ? `@${lib.version}` : ""}`;
    lines.push(`${label}${" ".repeat(Math.max(0, 38 - label.length))}│`);
  }
  lines.push(`├─────────────────────────────────────┤`);
  lines.push(`│        HAL / Framework Layer         │`);
  lines.push(`│  (${fw.framework})${" ".repeat(Math.max(0, 30 - fw.framework.length))}│`);
  lines.push(`├─────────────────────────────────────┤`);
  lines.push(`│           Hardware (MCU)             │`);
  lines.push(`│  ${mcu.model || mcu.family}${" ".repeat(Math.max(0, 34 - (mcu.model || mcu.family).length))}│`);
  lines.push(`└─────────────────────────────────────┘`);
  lines.push(`\`\`\``);
  lines.push(``);

  // Software Items
  lines.push(`## 3. Software Items (auto-generated)`);
  lines.push(``);
  lines.push(`Each component below maps to a firmware module or driver.`);
  lines.push(``);
  lines.push(`| # | Component | Type | GPIO Pins | Firmware Module |`);
  lines.push(`|---|-----------|------|-----------|-----------------|`);
  comps.forEach((c, i) => {
    const gpios = c.pins
      .filter((p) => p.gpio !== undefined)
      .map((p) => `GPIO${p.gpio}`)
      .join(", ");
    const module = c.type === "mcu" ? "core/hal" : `drivers/${c.type}`;
    lines.push(`| ${i + 1} | ${c.id} | ${c.type} | ${gpios || "—"} | ${module} |`);
  });
  lines.push(``);
  lines.push(`Total component count: **${comps.length}** (auto)`);
  lines.push(``);

  // Risk Classification
  lines.push(`## 4. Risk Classification`);
  lines.push(``);
  lines.push(`Per IEC 62304, software is classified into three safety classes:`);
  lines.push(``);
  lines.push(`| Class | Description | Applies? |`);
  lines.push(`|-------|-------------|----------|`);
  lines.push(`| **A** | No injury or damage to health possible | Most likely for this device |`);
  lines.push(`| **B** | Non-serious injury possible | Review if device provides clinical measurements |`);
  lines.push(`| **C** | Death or serious injury possible | Unlikely for Forge-class devices |`);
  lines.push(``);
  lines.push(`> **Recommendation**: Most MeshCue Forge devices fall under **Class A**`);
  lines.push(`> (low risk). If the device contributes to clinical decisions, reassess as Class B.`);
  lines.push(``);

  // Software Testing
  lines.push(`## 5. Software Testing`);
  lines.push(``);
  lines.push(`### 5.1 Unit Tests`);
  lines.push(`<!-- List unit tests for each software module -->`);
  lines.push(``);
  lines.push(`### 5.2 Integration Tests`);
  lines.push(`<!-- List integration tests verifying component interactions -->`);
  lines.push(``);
  lines.push(`### 5.3 System Tests`);
  lines.push(`<!-- List end-to-end tests for the complete firmware -->`);
  lines.push(``);
  lines.push(`### 5.4 Test reference`);
  lines.push(`- Framework: ${fw.framework}`);
  if (fw.features?.length) {
    lines.push(`- Features under test: ${fw.features.join(", ")}`);
  }
  lines.push(``);

  // Software Maintenance Plan
  lines.push(`## 6. Software Maintenance Plan`);
  lines.push(``);
  lines.push(`### 6.1 Firmware update mechanism`);
  lines.push(`<!-- Describe OTA or physical update process -->`);
  lines.push(``);
  lines.push(`### 6.2 Version control`);
  lines.push(`- Current version: ${doc.meta.version}`);
  lines.push(`- Schema version: ${doc.meta.schemaVersion}`);
  lines.push(``);
  lines.push(`### 6.3 Problem resolution process`);
  lines.push(`<!-- Describe bug reporting and fix process -->`);
  lines.push(``);

  // Class A simplified guidance
  lines.push(`## Appendix: Simplified Class A Guidance`);
  lines.push(``);
  lines.push(`For Class A software (no risk of injury), IEC 62304 requires:`);
  lines.push(``);
  lines.push(`1. **Software development planning** — this document`);
  lines.push(`2. **Software requirements** — derived from device requirements`);
  lines.push(`3. **Software architecture** — Section 2 above`);
  lines.push(`4. **Software unit verification** — basic testing of each module`);
  lines.push(`5. **Software release** — documented release with version number`);
  lines.push(`6. **Software maintenance** — Section 6 above`);
  lines.push(``);
  lines.push(`Class A does NOT require:`);
  lines.push(`- Detailed design documentation`);
  lines.push(`- Software integration testing (recommended but not mandatory)`);
  lines.push(`- Formal code reviews (recommended but not mandatory)`);

  return {
    stage: "docs",
    filename: "IEC62304_SOFTWARE_LIFECYCLE.md",
    content: lines.join("\n"),
    format: "markdown",
  };
}

// ─── 3. FMEA Template ──────────────────────────────────────

interface FMEARow {
  component: string;
  failureMode: string;
  effect: string;
  severity: number;
  occurrence: number;
  detection: number;
  action: string;
}

const FAILURE_MODES: Record<string, FMEARow[]> = {
  Sensor: [
    { component: "", failureMode: "Incorrect reading", effect: "Misdiagnosis or wrong treatment", severity: 8, occurrence: 3, detection: 4, action: "Implement plausibility checks and calibration routine" },
    { component: "", failureMode: "No reading", effect: "Loss of monitoring capability", severity: 7, occurrence: 2, detection: 2, action: "Add sensor timeout detection with alarm" },
    { component: "", failureMode: "Drift over time", effect: "Gradual measurement inaccuracy", severity: 6, occurrence: 4, detection: 5, action: "Schedule periodic recalibration; log drift metrics" },
  ],
  Display: [
    { component: "", failureMode: "Blank screen", effect: "No visual feedback to user", severity: 6, occurrence: 2, detection: 1, action: "Add audible backup alert; test display at boot" },
    { component: "", failureMode: "Incorrect display", effect: "Wrong information shown to clinician", severity: 8, occurrence: 2, detection: 3, action: "Implement display checksum / test pattern on boot" },
    { component: "", failureMode: "Dim / unreadable", effect: "Difficulty reading in bright environments", severity: 4, occurrence: 3, detection: 2, action: "Use high-contrast mode; allow brightness adjustment" },
  ],
  Button: [
    { component: "", failureMode: "Stuck", effect: "Continuous false input", severity: 5, occurrence: 2, detection: 2, action: "Debounce in firmware; detect stuck state" },
    { component: "", failureMode: "Unresponsive", effect: "Cannot operate device", severity: 6, occurrence: 2, detection: 2, action: "Add secondary input method or auto-mode" },
    { component: "", failureMode: "False trigger", effect: "Unintended action", severity: 5, occurrence: 3, detection: 3, action: "Require long-press or confirmation for critical actions" },
  ],
  Buzzer: [
    { component: "", failureMode: "No alarm", effect: "Critical alert missed", severity: 9, occurrence: 2, detection: 3, action: "Periodic buzzer self-test; add visual alarm backup" },
    { component: "", failureMode: "Continuous alarm", effect: "Alarm fatigue, user ignores alerts", severity: 5, occurrence: 2, detection: 1, action: "Implement alarm timeout and escalation protocol" },
    { component: "", failureMode: "Low volume", effect: "Alert not heard in noisy environment", severity: 7, occurrence: 3, detection: 4, action: "Test sound level at startup; use multi-tone alerts" },
  ],
  Power: [
    { component: "", failureMode: "Battery dead", effect: "Device shuts down unexpectedly", severity: 7, occurrence: 4, detection: 3, action: "Low-battery warning at 20%; graceful shutdown" },
    { component: "", failureMode: "Voltage drop", effect: "Erratic behaviour, sensor errors", severity: 6, occurrence: 3, detection: 4, action: "Add brown-out detection; voltage monitoring" },
    { component: "", failureMode: "Overheating", effect: "Device damage, burn risk", severity: 8, occurrence: 2, detection: 3, action: "Thermal cutoff; temperature monitoring on MCU" },
  ],
  MCU: [
    { component: "", failureMode: "Firmware crash", effect: "Complete device failure", severity: 8, occurrence: 2, detection: 2, action: "Enable watchdog timer; implement safe-state fallback" },
    { component: "", failureMode: "Watchdog reset", effect: "Temporary loss of function", severity: 5, occurrence: 3, detection: 2, action: "Log reset reason; verify state recovery after reset" },
    { component: "", failureMode: "Memory overflow", effect: "Firmware crash or data corruption", severity: 7, occurrence: 2, detection: 3, action: "Static allocation; stack canaries; memory monitoring" },
  ],
  Connection: [
    { component: "", failureMode: "Loose wire", effect: "Intermittent function loss", severity: 6, occurrence: 4, detection: 4, action: "Use soldered connections; strain relief; PCB traces" },
    { component: "", failureMode: "Corrosion", effect: "Gradual connection degradation", severity: 5, occurrence: 3, detection: 5, action: "Conformal coating; sealed enclosure; gold-plated contacts" },
    { component: "", failureMode: "Short circuit", effect: "Component damage, fire risk", severity: 9, occurrence: 2, detection: 3, action: "Add fuse / PTC resettable fuse; current-limiting" },
  ],
};

export function generateFMEATemplate(doc: MHDLDocument, lang?: MedicalLanguage): BuildArtifact {
  const comps = componentList(doc);
  const rows: string[] = [];

  rows.push(
    `# DISCLAIMER: This FMEA was auto-generated by MeshCue Forge as a design aid and starting point. It does NOT constitute regulatory approval or clinical validation. Review by qualified professionals is required.`,
  );
  rows.push(
    `Component,Failure Mode,Effect,Severity (1-10),Occurrence (1-10),Detection (1-10),RPN,Recommended Action`,
  );

  for (const comp of comps) {
    const cat = fmeaCategory(comp);
    const templates = FAILURE_MODES[cat];
    if (!templates) continue;

    for (const t of templates) {
      const rpn = t.severity * t.occurrence * t.detection;
      rows.push(
        `${comp.id},${t.failureMode},${t.effect},${t.severity},${t.occurrence},${t.detection},${rpn},${t.action}`,
      );
    }
  }

  return {
    stage: "docs",
    filename: "FMEA.csv",
    content: rows.join("\n"),
    format: "csv",
  };
}

// ─── 4. CE Guidance ─────────────────────────────────────────

export function generateCEGuidance(doc: MHDLDocument, lang?: MedicalLanguage): BuildArtifact {
  const s = t(lang);
  const lines: string[] = [];

  lines.push(MEDICAL_DISCLAIMER);
  lines.push(``);
  lines.push(`# ${s.ceGuidanceTitle}`);
  lines.push(`## ${deviceName(doc)}`);
  lines.push(``);
  lines.push(`> ${s.autoGenerated}.`);
  lines.push(``);

  // Classification guidance
  lines.push(`## 1. Device Classification`);
  lines.push(``);
  lines.push(`Under EU MDR 2017/745, medical devices are classified using Annex VIII rules.`);
  lines.push(``);
  lines.push(`| Class | Description | Typical Forge devices |`);
  lines.push(`|-------|-------------|----------------------|`);
  lines.push(`| **I** | Low risk, non-invasive | Environmental monitors, pill reminders |`);
  lines.push(`| **I** (measuring) | Low risk with measuring function | Thermometers, pulse counters |`);
  lines.push(`| **IIa** | Medium risk | Blood pressure monitors, diagnostic aids |`);
  lines.push(`| **IIb** | Medium-high risk | Infusion controllers, ventilator monitors |`);
  lines.push(`| **III** | High risk | Implantable devices (unlikely for Forge) |`);
  lines.push(``);
  lines.push(`> **Most MeshCue Forge devices are Class I or Class I (measuring).**`);
  lines.push(`> Review Annex VIII classification rules to confirm.`);
  lines.push(``);

  // Required documentation
  lines.push(`## 2. Technical Documentation (Annex II & III)`);
  lines.push(``);
  lines.push(`The Technical File must contain:`);
  lines.push(``);
  lines.push(`- [ ] Device description and specification (see WHO_CHECKLIST.md)`);
  lines.push(`- [ ] Design and manufacturing information`);
  lines.push(`- [ ] General safety and performance requirements (Annex I)`);
  lines.push(`- [ ] Benefit-risk analysis and risk management (ISO 14971)`);
  lines.push(`- [ ] Product verification and validation`);
  lines.push(`- [ ] Pre-clinical and clinical evaluation`);
  lines.push(`- [ ] Post-market surveillance plan`);
  lines.push(`- [ ] Labeling and Instructions for Use`);
  lines.push(``);

  // Simplified path for Class I
  lines.push(`## 3. Simplified Path for Class I Devices`);
  lines.push(``);
  lines.push(`Class I devices (non-measuring, non-sterile) benefit from a simplified path:`);
  lines.push(``);
  lines.push(`1. **No Notified Body required** — self-declaration of conformity`);
  lines.push(`2. Prepare Technical Documentation (Annex II)`);
  lines.push(`3. Establish Quality Management System (Annex IX, Chapter I)`);
  lines.push(`4. Draft EU Declaration of Conformity (Annex IV)`);
  lines.push(`5. Register in EUDAMED database`);
  lines.push(`6. Appoint EU Authorized Representative (if manufacturer is outside EU)`);
  lines.push(`7. Assign UDI (Unique Device Identification)`);
  lines.push(`8. Affix CE mark to device and packaging`);
  lines.push(``);
  lines.push(`> **Class I (measuring)** and **Class I (sterile)** DO require a`);
  lines.push(`> Notified Body for the measuring/sterile aspects.`);
  lines.push(``);

  // Notified Body requirements
  lines.push(`## 4. Notified Body Requirements (Class IIa and above)`);
  lines.push(``);
  lines.push(`If your device is classified as Class IIa or higher:`);
  lines.push(``);
  lines.push(`- A Notified Body must perform conformity assessment`);
  lines.push(`- Conformity assessment routes: Annex IX (QMS) or Annex XI (product examination)`);
  lines.push(`- Expect 6–18 months for Notified Body review`);
  lines.push(`- Budget EUR 10,000–50,000+ for certification costs`);
  lines.push(`- Maintain QMS per ISO 13485 throughout product lifecycle`);
  lines.push(``);

  // Harmonized standards
  lines.push(`## 5. Harmonized Standards`);
  lines.push(``);
  lines.push(`Key standards for electronic medical devices:`);
  lines.push(``);
  lines.push(`| Standard | Title | Relevance |`);
  lines.push(`|----------|-------|-----------|`);
  lines.push(`| EN 60601-1 | Medical electrical equipment — General requirements | Electrical safety |`);
  lines.push(`| EN 60601-1-2 | EMC requirements and tests | Electromagnetic compatibility |`);
  lines.push(`| EN 60601-1-6 | Usability | User interface design |`);
  lines.push(`| EN 60601-1-8 | Alarm systems | If device has alarms |`);
  lines.push(`| EN 62304 | Software lifecycle | Firmware (see IEC62304 doc) |`);
  lines.push(`| EN ISO 14971 | Risk management | FMEA and risk analysis |`);
  lines.push(`| EN ISO 10993 | Biocompatibility | If patient-contacting |`);
  lines.push(`| EN 62366-1 | Usability engineering | User interface |`);
  lines.push(``);

  // Device-specific info
  lines.push(`## 6. Device-Specific Information (auto-generated)`);
  lines.push(``);
  lines.push(`- **Device name**: ${deviceName(doc)}`);
  lines.push(`- **Power input**: ${powerVoltage(doc)}`);
  lines.push(`- **Max current**: ${maxCurrent(doc)}`);
  lines.push(`- **Enclosure**: ${doc.enclosure.type}, ${enclosureMaterial(doc)}`);
  lines.push(`- **Connectivity**: ${doc.board.mcu.wireless?.join(", ") || "None"}`);
  lines.push(`- **Component count**: ${componentList(doc).length}`);

  return {
    stage: "docs",
    filename: "CE_GUIDANCE.md",
    content: lines.join("\n"),
    format: "markdown",
  };
}

// ─── 5. Battery Life Estimate ───────────────────────────────

interface BatteryOption {
  name: string;
  capacityMah: number;
  voltage: number;
}

const BATTERY_OPTIONS: BatteryOption[] = [
  { name: "18650 Li-Ion", capacityMah: 3400, voltage: 3.7 },
  { name: "2x AA Alkaline", capacityMah: 2500, voltage: 3.0 },
  { name: "CR2032 Coin Cell", capacityMah: 220, voltage: 3.0 },
  { name: "LiPo 1000mAh", capacityMah: 1000, voltage: 3.7 },
  { name: "LiPo 2000mAh", capacityMah: 2000, voltage: 3.7 },
];

/** Rough current draw by component type (mA, active state) */
function estimateComponentCurrentMa(comp: Component): number {
  const t = comp.type;
  if (t === "mcu") return 80;
  if (t === "oled") return 20;
  if (t === "lcd") return 25;
  if (t === "led" || t === "neopixel") return 20;
  if (t === "buzzer" || t === "speaker") return 30;
  if (["sensor", "temperature_sensor", "thermocouple", "moisture", "gas_sensor", "ldr", "pir"].includes(t))
    return 5;
  if (t === "ultrasonic") return 15;
  if (t === "gps") return 50;
  if (t === "rfid") return 30;
  if (["motor", "servo", "stepper"].includes(t)) return 200;
  if (t === "relay") return 70;
  return 5; // default for passive or low-power components
}

export function generateBatteryLifeEstimate(doc: MHDLDocument, lang?: MedicalLanguage): BuildArtifact {
  const comps = componentList(doc);
  const mcu = doc.board.mcu;
  const lines: string[] = [];

  // Calculate current draws
  const currentBreakdown: { name: string; activeMa: number; dutyPct: number; avgMa: number }[] = [];

  for (const comp of comps) {
    const activeMa = estimateComponentCurrentMa(comp);
    let dutyPct: number;

    // Assign duty cycles based on type
    if (comp.type === "mcu") {
      dutyPct = 100; // always on
    } else if (
      ["sensor", "temperature_sensor", "thermocouple", "moisture", "gas_sensor", "ldr", "pir", "ultrasonic", "gps", "rfid"].includes(
        comp.type,
      )
    ) {
      dutyPct = 10; // reads every ~10s, active ~1s
    } else if (["oled", "lcd", "led", "neopixel"].includes(comp.type)) {
      dutyPct = 50; // display on 50% of time
    } else if (["buzzer", "speaker"].includes(comp.type)) {
      dutyPct = 2; // alarm rarely active
    } else if (["motor", "servo", "stepper"].includes(comp.type)) {
      dutyPct = 5; // intermittent actuation
    } else {
      dutyPct = 10;
    }

    const avgMa = activeMa * (dutyPct / 100);
    currentBreakdown.push({ name: comp.id, activeMa, dutyPct, avgMa });
  }

  // WiFi burst estimate
  const hasWifi = mcu.wireless?.includes("wifi");
  const hasBle = mcu.wireless?.includes("ble") || mcu.wireless?.includes("bluetooth");
  if (hasWifi) {
    currentBreakdown.push({ name: "WiFi (burst)", activeMa: 170, dutyPct: 5, avgMa: 8.5 });
  }
  if (hasBle) {
    currentBreakdown.push({ name: "BLE (advertising)", activeMa: 15, dutyPct: 10, avgMa: 1.5 });
  }

  const totalAvgMa = currentBreakdown.reduce((sum, c) => sum + c.avgMa, 0);

  const s = t(lang);

  lines.push(MEDICAL_DISCLAIMER);
  lines.push(``);
  lines.push(`# ${s.batteryLifeTitle}`);
  lines.push(`## ${deviceName(doc)}`);
  lines.push(``);
  lines.push(`> ${s.autoGenerated}.`);
  lines.push(``);

  // Current draw breakdown
  lines.push(`## 1. ${s.currentDrawBreakdown}`);
  lines.push(``);
  lines.push(`| ${s.component} | Active (mA) | Duty Cycle | Average (mA) |`);
  lines.push(`|-----------|-------------|------------|--------------|`);
  for (const c of currentBreakdown) {
    lines.push(`| ${c.name} | ${c.activeMa} | ${c.dutyPct}% | ${c.avgMa.toFixed(1)} |`);
  }
  lines.push(`| **Total** | | | **${totalAvgMa.toFixed(1)}** |`);
  lines.push(``);

  // Duty cycle assumptions
  lines.push(`## 2. ${s.dutyCycleAssumptions}`);
  lines.push(``);
  lines.push(`- Sensor reads: every 10 seconds (1s active, 9s sleep)`);
  lines.push(`- Display: on 50% of the time (user interaction or continuous readout)`);
  lines.push(`- Buzzer/alarm: active 2% of the time (periodic alerts)`);
  if (hasWifi) lines.push(`- WiFi: burst every 5 minutes, ~3s per burst (5% duty)`);
  if (hasBle) lines.push(`- BLE: advertising at 10% duty cycle`);
  lines.push(`- MCU: always on (no deep sleep assumed)`);
  lines.push(``);

  // Battery life estimates
  lines.push(`## 3. ${s.estimatedBatteryLife}`);
  lines.push(``);
  lines.push(`| Battery | Capacity | Voltage | Est. Hours | Est. Days |`);
  lines.push(`|---------|----------|---------|------------|-----------|`);

  let recommendedBattery = BATTERY_OPTIONS[0];
  let bestScore = 0;

  for (const bat of BATTERY_OPTIONS) {
    const hours = bat.capacityMah / totalAvgMa;
    const days = hours / 24;
    lines.push(
      `| ${bat.name} | ${bat.capacityMah} mAh | ${bat.voltage}V | ${hours.toFixed(1)} | ${days.toFixed(1)} |`,
    );

    // Scoring: prefer 2+ days of runtime, penalise overkill
    const dayScore = Math.min(days, 30) / 30;
    if (dayScore > bestScore) {
      bestScore = dayScore;
      recommendedBattery = bat;
    }
  }
  lines.push(``);

  // Recommendation
  lines.push(`## 4. ${s.recommendation}`);
  lines.push(``);
  const recHours = recommendedBattery.capacityMah / totalAvgMa;
  const recDays = recHours / 24;
  lines.push(`**Recommended battery**: ${recommendedBattery.name} (${recommendedBattery.capacityMah} mAh)`);
  lines.push(`- Estimated runtime: ${recHours.toFixed(1)} hours (${recDays.toFixed(1)} days)`);
  lines.push(`- Voltage: ${recommendedBattery.voltage}V`);
  lines.push(``);
  if (totalAvgMa < 10) {
    lines.push(`> This device has very low power consumption. A CR2032 coin cell`);
    lines.push(`> may be sufficient for months of operation.`);
  } else if (totalAvgMa < 50) {
    lines.push(`> Moderate power consumption. A single 18650 or LiPo 2000mAh cell`);
    lines.push(`> should provide multiple days of continuous operation.`);
  } else {
    lines.push(`> Relatively high power consumption. Consider a large LiPo or`);
    lines.push(`> 18650 cell, and implement aggressive power management (deep sleep).`);
  }
  lines.push(``);

  // Solar panel sizing
  lines.push(`## 5. ${s.solarPanelSizing}`);
  lines.push(``);
  const avgWatts = (totalAvgMa / 1000) * 3.7; // assume 3.7V system
  const solarHoursPerDay = 4; // conservative for tropical regions
  const panelEfficiency = 0.7; // losses from charge controller, angle, etc.
  const panelWatts = avgWatts / (solarHoursPerDay / 24) / panelEfficiency;
  lines.push(`- Average power consumption: ${(avgWatts * 1000).toFixed(0)} mW`);
  lines.push(`- Assumed peak solar hours: ${solarHoursPerDay} h/day (tropical/subtropical)`);
  lines.push(`- Charge controller efficiency: ${(panelEfficiency * 100).toFixed(0)}%`);
  lines.push(`- **Minimum solar panel**: ${panelWatts.toFixed(2)} W`);
  lines.push(`- **Recommended solar panel**: ${(panelWatts * 1.5).toFixed(2)} W (1.5x margin)`);
  lines.push(``);
  lines.push(`> For reliable outdoor deployment, pair the solar panel with a`);
  lines.push(`> LiPo 2000mAh+ battery to cover cloudy days and nighttime operation.`);

  return {
    stage: "docs",
    filename: "BATTERY_LIFE_ESTIMATE.md",
    content: lines.join("\n"),
    format: "markdown",
  };
}

// ─── 6. Field Test Checklist ────────────────────────────────

export function generateFieldTestChecklist(doc: MHDLDocument, lang?: MedicalLanguage): BuildArtifact {
  const comps = componentList(doc);
  const lines: string[] = [];

  const str = t(lang);

  lines.push(MEDICAL_DISCLAIMER);
  lines.push(``);
  lines.push(`# ${str.fieldTestChecklist}`);
  lines.push(`## ${deviceName(doc)}`);
  lines.push(``);
  lines.push(`> ${str.autoGenerated}.`);
  lines.push(``);

  // ── 1. Functional Testing ──
  lines.push(`## 1. ${str.functionalTesting}`);
  lines.push(``);

  // Sensor checks
  const sensors = comps.filter((c) =>
    [
      "sensor", "temperature_sensor", "thermocouple", "moisture",
      "gas_sensor", "ldr", "pir", "ultrasonic", "gps", "rfid",
    ].includes(c.type),
  );
  if (sensors.length > 0) {
    for (const s of sensors) {
      lines.push(`- [ ] **${s.id}** (${s.type}${s.model ? `, ${s.model}` : ""}): reads within expected range`);
    }
  } else {
    lines.push(`- [ ] All sensor inputs read within expected range`);
  }

  // Display checks
  const displays = comps.filter((c) =>
    ["oled", "lcd", "neopixel", "led"].includes(c.type),
  );
  if (displays.length > 0) {
    for (const d of displays) {
      lines.push(`- [ ] **${d.id}** (${d.type}): displays correct values / status`);
    }
  } else {
    lines.push(`- [ ] Display shows correct values`);
  }

  // Button checks
  const buttons = comps.filter((c) =>
    ["button", "joystick", "potentiometer", "encoder"].includes(c.type),
  );
  if (buttons.length > 0) {
    for (const b of buttons) {
      lines.push(`- [ ] **${b.id}** (${b.type}): responds to user input`);
    }
  } else {
    lines.push(`- [ ] All buttons / inputs respond correctly`);
  }

  // Buzzer / alarm checks
  const buzzers = comps.filter((c) => ["buzzer", "speaker"].includes(c.type));
  if (buzzers.length > 0) {
    for (const bz of buzzers) {
      lines.push(`- [ ] **${bz.id}** (${bz.type}): alarm triggers at threshold`);
    }
  } else {
    lines.push(`- [ ] Buzzer / alarm triggers at threshold (if applicable)`);
  }

  // Connectivity checks
  const mcu = doc.board.mcu;
  if (mcu.wireless?.includes("wifi")) {
    lines.push(`- [ ] WiFi connects to access point and transmits data`);
  }
  if (mcu.wireless?.includes("ble") || mcu.wireless?.includes("bluetooth")) {
    lines.push(`- [ ] BLE advertising is visible and pairing works`);
  }
  lines.push(``);

  // ── 2. Safety Testing ──
  lines.push(`## 2. ${str.safetyTesting}`);
  lines.push(``);
  lines.push(`- [ ] No exposed conductors or solder joints accessible to user`);
  lines.push(`- [ ] Enclosure is sealed (perform IP spray test if rated)`);
  lines.push(`- [ ] No sharp edges on enclosure or components`);
  lines.push(`- [ ] Battery is secure and cannot shift during normal handling`);
  lines.push(`- [ ] No overheating after 1 hour of continuous operation (measure with IR thermometer)`);
  lines.push(`- [ ] Fuse / overcurrent protection verified (if applicable)`);
  lines.push(``);

  // ── 3. Accuracy Testing ──
  lines.push(`## 3. ${str.accuracyTesting}`);
  lines.push(``);
  lines.push(`For each sensor, compare 10 measurements against a reference device and calculate mean error.`);
  lines.push(``);

  if (sensors.length > 0) {
    lines.push(`| Sensor | Reference Device | Measurements | Mean Error | Acceptable Tolerance | Pass? |`);
    lines.push(`|--------|-----------------|--------------|------------|---------------------|-------|`);
    for (const s of sensors) {
      let tolerance = "TBD";
      const t = s.type;
      const model = (s.model || "").toLowerCase();
      if (t === "temperature_sensor" || t === "thermocouple" || model.includes("temp") || model.includes("ds18b20") || model.includes("dht")) {
        tolerance = "±0.3°C";
      } else if (model.includes("max301") || model.includes("spo2") || model.includes("pulse")) {
        tolerance = "±2% SpO2";
      } else if (model.includes("bp") || model.includes("blood") || model.includes("pressure")) {
        tolerance = "±3 mmHg";
      } else if (t === "moisture" || t === "gas_sensor" || t === "ldr") {
        tolerance = "±5%";
      } else if (t === "ultrasonic") {
        tolerance = "±1 cm";
      } else if (t === "gps") {
        tolerance = "±5 m CEP";
      }
      lines.push(`| ${s.id} | | 10 readings | | ${tolerance} | [ ] |`);
    }
  } else {
    lines.push(`| Sensor | Reference Device | Measurements | Mean Error | Acceptable Tolerance | Pass? |`);
    lines.push(`|--------|-----------------|--------------|------------|---------------------|-------|`);
    lines.push(`| (list sensors) | | 10 readings | | TBD | [ ] |`);
  }
  lines.push(``);

  // ── 4. Battery Testing ──
  lines.push(`## 4. ${str.batteryTesting}`);
  lines.push(``);
  lines.push(`- [ ] Measure actual battery life vs. estimated (see BATTERY_LIFE_ESTIMATE.md)`);
  lines.push(`  - Estimated: ______ hours`);
  lines.push(`  - Actual: ______ hours`);
  lines.push(`  - Ratio (actual/estimated): ______`);
  lines.push(`- [ ] Low-battery warning triggers at 20% remaining capacity`);
  lines.push(`- [ ] Graceful shutdown occurs at 5% remaining capacity`);
  lines.push(`- [ ] Device recovers correctly after full battery drain and recharge`);
  lines.push(``);

  // ── 5. Environmental Testing ──
  lines.push(`## 5. ${str.environmentalTesting}`);
  lines.push(``);
  lines.push(`- [ ] Operate at **40°C** for 1 hour — verify stable sensor readings and no overheating`);
  lines.push(`- [ ] Operate at **high humidity** (>80% RH) for 1 hour — verify no condensation on electronics`);
  lines.push(`- [ ] **Drop test**: drop assembled device from 1 m onto concrete`);
  lines.push(`  - [ ] Enclosure intact (no cracks or separation)`);
  lines.push(`  - [ ] Device powers on and functions after drop`);
  lines.push(`  - [ ] No loose internal components after drop`);
  if (doc.enclosure.ipRating) {
    lines.push(`- [ ] **IP rating test (${doc.enclosure.ipRating})**: verify per IEC 60529 requirements`);
  }
  lines.push(``);

  // ── 6. Documentation ──
  lines.push(`## 6. Documentation`);
  lines.push(``);
  lines.push(`- [ ] Serial number assigned: ________________`);
  lines.push(`- [ ] Calibration date recorded: ____/____/________`);
  lines.push(`- [ ] Operator trained on device use`);
  lines.push(`- [ ] Patient information leaflet available`);
  lines.push(`- [ ] Instructions for Use (IFU) included with device`);
  lines.push(`- [ ] Maintenance schedule documented`);
  lines.push(`- [ ] Contact information for technical support provided`);
  lines.push(``);

  // ── Sign-off ──
  lines.push(`## Sign-off`);
  lines.push(``);
  lines.push(`| Role | Name | Signature | Date |`);
  lines.push(`|------|------|-----------|------|`);
  lines.push(`| Tester | | | |`);
  lines.push(`| Reviewer | | | |`);
  lines.push(`| Approver | | | |`);

  return {
    stage: "docs",
    filename: "FIELD_TEST_CHECKLIST.md",
    content: lines.join("\n"),
    format: "markdown",
  };
}
